spring:
  datasource:
    url: jdbc:postgresql://${db_host}:${db_port}/${db_name}
    username: ${db_user}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      default_schema: public
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect