export const TRANSACTION_TYPES = {
  EXPENSE: 'EXPENSE',
  INCOME: 'INCOME',
};

export const CURRENCIES = [
  { id: 30, name: 'Emirati Dirham', symbol: 'AED' },
  { id: 72, name: 'Albanian Lek', symbol: 'ALL' },
  { id: 66, name: 'Armenian Dram', symbol: 'AMD' },
  { id: 5, name: 'Australian Dollar', symbol: 'AUD' },
  { id: 85, name: 'Aruban Florin', symbol: 'AWG' },
  { id: 52, name: 'Azerbaijani Manat', symbol: 'AZN' },
  {
    id: 80,
    name: 'Bosnia-Herzegovina Convertible Mark',
    symbol: 'BAM',
  },
  { id: 39, name: 'Bangladeshi Taka', symbol: 'BDT' },
  { id: 64, name: 'Bulgarian Lev', symbol: 'BGN' },
  { id: 49, name: 'Bahraini Dinar', symbol: 'BHD' },
  { id: 59, name: 'Bolivian Boliviano', symbol: 'BOB' },
  { id: 19, name: 'Brazilian Real', symbol: 'BRL' },
  { id: 82, name: 'Botswanan Pula', symbol: 'BWP' },
  { id: 51, name: 'Belarusian Ruble', symbol: 'BYN' },
  { id: 6, name: 'Canadian Dollar', symbol: 'CAD' },
  { id: 7, name: 'Swiss Franc', symbol: 'CHF' },
  { id: 28, name: 'Chilean Peso', symbol: 'CLP' },
  { id: 8, name: 'Chinese Yuan', symbol: 'CNY' },
  { id: 31, name: 'Colombian Peso', symbol: 'COP' },
  { id: 42, name: 'Costa Rican Colon', symbol: 'CRC' },
  { id: 88, name: 'Cuban Convertible Peso', symbol: 'CUC' },
  { id: 26, name: 'Czech Koruna', symbol: 'CZK' },
  { id: 21, name: 'Danish Krone', symbol: 'DKK' },
  { id: 63, name: 'Dominican Peso', symbol: 'DOP' },
  { id: 68, name: 'Algerian Dinar', symbol: 'DZD' },
  { id: 43, name: 'Egyptian Pound', symbol: 'EGP' },
  { id: 78, name: 'Ethiopian Birr', symbol: 'ETB' },
  { id: 2, name: 'Euro', symbol: 'EUR' },
  { id: 4, name: 'British Pound', symbol: 'GBP' },
  { id: 57, name: 'Georgian Lari', symbol: 'GEL' },
  { id: 76, name: 'Ghanaian Cedi', symbol: 'GHS' },
  { id: 50, name: 'Guatemalan Quetzal', symbol: 'GTQ' },
  { id: 20, name: 'Hong Kong Dollar', symbol: 'HKD' },
  { id: 61, name: 'Honduran Lempira', symbol: 'HNL' },
  { id: 65, name: 'Croatian Kuna', symbol: 'HRK' },
  { id: 25, name: 'Hungarian Forint', symbol: 'HUF' },
  { id: 24, name: 'Indonesian Rupiah', symbol: 'IDR' },
  { id: 27, name: 'Israeli Shekel', symbol: 'ILS' },
  { id: 15, name: 'Indian Rupee', symbol: 'INR' },
  { id: 60, name: 'Icelandic Krona', symbol: 'ISK' },
  { id: 84, name: 'Jamaican Dollar', symbol: 'JMD' },
  { id: 48, name: 'Jordanian Dinar', symbol: 'JOD' },
  { id: 3, name: 'Japanese Yen', symbol: 'JPY' },
  { id: 38, name: 'Kenyan Shilling', symbol: 'KES' },
  { id: 86, name: 'Cambodian Riel', symbol: 'KHR' },
  { id: 13, name: 'South Korean Won', symbol: 'KRW' },
  { id: 44, name: 'Kuwaiti Dinar', symbol: 'KWD' },
  { id: 55, name: 'Kazakhstani Tenge', symbol: 'KZT' },
  { id: 74, name: 'Lebanese Pound', symbol: 'LBP' },
  { id: 71, name: 'Sri Lankan Rupee', symbol: 'LKR' },
  { id: 70, name: 'Lithuanian Litas', symbol: 'LTL' },
  { id: 46, name: 'Moroccan Dirham', symbol: 'MAD' },
  { id: 56, name: 'Moldovan Leu', symbol: 'MDL' },
  { id: 69, name: 'Macedonian Denar', symbol: 'MKD' },
  { id: 58, name: 'Myanmar Kyat', symbol: 'MMK' },
  { id: 90, name: 'Mauritanian Ouguiya', symbol: 'MRU' },
  { id: 89, name: 'Maldivian Rufiyaa', symbol: 'MVR' },
  { id: 14, name: 'Mexican Peso', symbol: 'MXN' },
  { id: 33, name: 'Malaysian Ringgit', symbol: 'MYR' },
  { id: 81, name: 'Mozambican Metical', symbol: 'MZN' },
  { id: 83, name: 'Namibian Dollar', symbol: 'NAD' },
  { id: 36, name: 'Nigerian Naira', symbol: 'NGN' },
  { id: 67, name: 'Nicaraguan Cordoba', symbol: 'NIO' },
  { id: 12, name: 'Norwegian Krone', symbol: 'NOK' },
  { id: 75, name: 'Nepalese Rupee', symbol: 'NPR' },
  { id: 10, name: 'New Zealand Dollar', symbol: 'NZD' },
  { id: 47, name: 'Omani Rial', symbol: 'OMR' },
  { id: 53, name: 'Panamanian Balboa', symbol: 'PAB' },
  { id: 35, name: 'Peruvian Sol', symbol: 'PEN' },
  { id: 29, name: 'Philippine Peso', symbol: 'PHP' },
  { id: 22, name: 'Polish Zloty', symbol: 'PLN' },
  { id: 73, name: 'Paraguayan Guarani', symbol: 'PYG' },
  { id: 41, name: 'Qatari Riyal', symbol: 'QAR' },
  { id: 34, name: 'Romanian Leu', symbol: 'RON' },
  { id: 16, name: 'Russian Ruble', symbol: 'RUB' },
  { id: 32, name: 'Saudi Riyal', symbol: 'SAR' },
  { id: 9, name: 'Swedish Krona', symbol: 'SEK' },
  { id: 11, name: 'Singapore Dollar', symbol: 'SGD' },
  { id: 87, name: 'Sierra Leonean Leone', symbol: 'SLL' },
  { id: 23, name: 'Thai Baht', symbol: 'THB' },
  { id: 62, name: 'Tunisian Dinar', symbol: 'TND' },
  { id: 18, name: 'Turkish Lira', symbol: 'TRY' },
  { id: 45, name: 'New Taiwan Dollar', symbol: 'TWD' },
  { id: 77, name: 'Tanzanian Shilling', symbol: 'TZS' },
  { id: 40, name: 'Ukrainian Hryvnia', symbol: 'UAH' },
  { id: 79, name: 'Ugandan Shilling', symbol: 'UGX' },
  { id: 54, name: 'Uruguayan Peso', symbol: 'UYU' },
  { id: 37, name: 'Vietnamese Dong', symbol: 'VND' },
  { id: 17, name: 'South African Rand', symbol: 'ZAR' },
];
