INSERT INTO currencies (name, symbol) VALUES
('United States Dollar', 'USD'),
('Euro', 'EUR'),
('Japanese Yen', 'JPY'),
('British Pound', 'GBP'),
('Australian Dollar', 'AUD'),
('Canadian Dollar', 'CAD'),
('Swiss Franc', 'CHF'),
('Chinese Yuan', 'CNY'),
('Swedish Krona', 'SEK'),
('New Zealand Dollar', 'NZD'),
('Singapore Dollar', 'SGD'),
('Norwegian Krone', 'NOK'),
('South Korean Won', 'KRW'),
('Mexican Peso', 'MXN'),
('Indian Rupee', 'INR'),
('Russian Ruble', 'RUB'),
('South African Rand', 'ZAR'),
('Turkish Lira', 'TRY'),
('Brazilian Real', 'BRL'),
('Hong Kong Dollar', 'HKD'),
('Danish Krone', 'DKK'),
('Polish Zloty', 'PLN'),
('Thai Baht', 'THB'),
('Indonesian Rupiah', 'IDR'),
('Hungarian Forint', 'HUF'),
('Czech Koruna', 'CZK'),
('Israeli Shekel', 'ILS'),
('Chilean Peso', 'CLP'),
('Philippine Peso', 'PHP'),
('Emirati Dirham', 'AED'),
('Colombian Peso', 'COP'),
('Saudi Riyal', 'SAR'),
('Malaysian Ringgit', 'MYR'),
('Romanian Leu', 'RON'),
('Peruvian Sol', 'PEN'),
('Nigerian Naira', 'NGN'),
('Vietnamese Dong', 'VND'),
('Kenyan Shilling', 'KES'),
('Bangladeshi Taka', 'BDT'),
('Ukrainian Hryvnia', 'UAH'),
('Qatari Riyal', 'QAR'),
('Costa Rican Colon', 'CRC'),
('Egyptian Pound', 'EGP'),
('Kuwaiti Dinar', 'KWD'),
('New Taiwan Dollar', 'TWD'),
('Moroccan Dirham', 'MAD'),
('Omani Rial', 'OMR'),
('Jordanian Dinar', 'JOD'),
('Bahraini Dinar', 'BHD'),
('Guatemalan Quetzal', 'GTQ'),
('Belarusian Ruble', 'BYN'),
('Azerbaijani Manat', 'AZN'),
('Panamanian Balboa', 'PAB'),
('Uruguayan Peso', 'UYU'),
('Kazakhstani Tenge', 'KZT'),
('Moldovan Leu', 'MDL'),
('Georgian Lari', 'GEL'),
('Myanmar Kyat', 'MMK'),
('Bolivian Boliviano', 'BOB'),
('Icelandic Krona', 'ISK'),
('Honduran Lempira', 'HNL'),
('Tunisian Dinar', 'TND'),
('Dominican Peso', 'DOP'),
('Bulgarian Lev', 'BGN'),
('Croatian Kuna', 'HRK'),
('Armenian Dram', 'AMD'),
('Nicaraguan Cordoba', 'NIO'),
('Algerian Dinar', 'DZD'),
('Macedonian Denar', 'MKD'),
('Lithuanian Litas', 'LTL'),
('Sri Lankan Rupee', 'LKR'),
('Albanian Lek', 'ALL'),
('Paraguayan Guarani', 'PYG'),
('Lebanese Pound', 'LBP'),
('Nepalese Rupee', 'NPR'),
('Ghanaian Cedi', 'GHS'),
('Tanzanian Shilling', 'TZS'),
('Ethiopian Birr', 'ETB'),
('Ugandan Shilling', 'UGX'),
('Bosnia-Herzegovina Convertible Mark', 'BAM'),
('Mozambican Metical', 'MZN'),
('Botswanan Pula', 'BWP'),
('Namibian Dollar', 'NAD'),
('Jamaican Dollar', 'JMD'),
('Aruban Florin', 'AWG'),
('Cambodian Riel', 'KHR'),
('Sierra Leonean Leone', 'SLL'),
('Cuban Convertible Peso', 'CUC'),
('Maldivian Rufiyaa', 'MVR'),
('Mauritanian Ouguiya', 'MRU'),
('Mauritanian Ouguiya', 'MRU');